# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c9584fdb2a3e1a5f9ba852f7a4b6c059ba11203e295503923fb91d46b762ca2e82f78fee5e5812d8dcedefea97427979b6c7ff52ee68bc198987598b2af725a

test:
  secret_key_base: c7ac362396d9166d69eb0eeef7d5b7eaaecb24df956067c9141ad998d0c8507f7e0a7ab00d806f7d599e7685f81687f7fde20c63a669033bcd349da3efe49f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



